name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted  # This will run on your home server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build inside Docker
        run: |
          docker run --rm --net=custom_network --mac-address=4c:cc:6a:06:b3:79 \
          -v /opt/build-tools:/mnt/build-tools:ro \
          -v $GITHUB_WORKSPACE:/mnt/project:rw my_docker_image /bin/bash -c "cd /mnt/project && make"
